name: Python CI/CD Workflow

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Change to your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file

      - name: Run Tests
        run: |
          pytest test_app.py  # Replace with your test file name
     
  deploy:
    runs-on: ubuntu-latest
    steps:         
    - name: deployment step
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          cd /home/ubuntu/
          git config --global user.email "lokesh.sayana@gmail.com"
          git config --global user.name "sayanalokesh"
          # Add the remote repository URL
          git remote add origin_with_token https://sayanalokesh:${{ secrets.ACCESS_TOKEN }}@github.com/sayanalokesh/GithubActionsNew.git
          git clone https://github.com/sayanalokesh/GithubActionsNew.git
          cd GithubActionsNew
          sudo ls
          sudo git checkout staging
          sudo echo "checked out to staging branch"
          sudo git pull
          sudo echo "pull has been successful"
          sudo apt install -y python3-pip
          pip install flask
          pip install gunicorn        
          python3 app.py
          nohup sudo gunicorn -w 4 -b 0.0.0.0:3000 app:app >/dev/null 2>&1 &
          echo "app is up and running fine"
          sudo git checkout production
          echo "checked out to production branch"
          sudo git pull
          echo "pull has been successful"
          sudo git merge staging
          echo "merge successful"
          sudo git push origin_with_token production
          echo "pushed to production"
          sudo git tag -a v1.0
          sudo git push origin_with_token v1.0
          # sudo python3 /home/ubuntu/Jenkins/app.py
          

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST1 }}  # Replace with your production server IP
          username: ${{ secrets.EC2_USERNAME }}  # Replace with your SSH username
          key: ${{ secrets.EC2_SSH_KEY }}  # Replace with your SSH private key
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/
            git clone https://github.com/sayanalokesh/GithubActionsNew.git
            sudo git checkout production
            sudo apt install -y python3-pip
            pip install flask
            pip install gunicorn
            nohup sudo gunicorn -w 4 -b 0.0.0.0:3000 app:app >/dev/null 2>&1 &
          # sudo python3 /home/ubuntu/Jenkins/app.py# Commands to deploy to production server
            # ssh -i ${{secrets.EC2_SSH_KEY}} ubuntu@ec2-52-66-160-84.ap-south-1.compute.amazonaws.com "ls"  # "cd /home/ubuntu && git pull origin staging && sudo systemctl restart jenkins"
